### ISSUE TITLE
Change LICENSE to MIT

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/first-issues#100]

**Comment by arshadkazmi42** [comment]
@kgashok Need your input on this. I was thinking of changing the license of this project to MIT. To make it more available for other open source contributors.

Any thoughts on this?

**Comment by Aayush3014** [comment]
Hii, if this issue is still open please let me solve this issue and try to change the license to MIT License.
Please, assign me this issue if it is still available.

**Comment by kgashok** [comment]
> @kgashok Need your input on this. I was thinking of changing the license of this project to MIT. To make it more available for other open source contributors.
> 
> Any thoughts on this?

Yes, go ahead.
