### ISSUE TITLE
Change github workflow to run on pull request

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/first-issues#102]
Change this line

https://github.com/arshadkazmi42/first-issues/blob/master/.github/workflows/pytest.yml#L3

similar to these lines

https://github.com/gh-conf/rhof/blob/master/.github/workflows/nodejs.yml#L3-L5

**Comment by SubinDuresh** [comment]
HI @arshadkazmi42 , I am interested in working on this. Can you assign it to me?

**Comment by arshadkazmi42** [comment]
Assigned
