### ISSUE TITLE
Add Install dependencies step 

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/first-issues#26]
Add a install dependency step in usage docs.

`pip install -r requirements.txt`

**Comment by SubhamPaul21** [comment]
I want to work on this ... May I?

**Comment by SubhamPaul21** [comment]
May I do the required changes?

**Comment by arshadkazmi42** [comment]
Yes please. Go ahead.

**Comment by SubhamPaul21** [comment]
sent a PR. please have a look

**Comment by SubhamPaul21** [comment]
sent PR ... have a look
