### ISSUE TITLE
Change twitter and telegram url to display logos

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/first-issues#47]
Let change this
`You can follow the twitter account @first_issues or telegram channel @first_issues`

to show logo of twitter and telegram which will have hyperlink to the specific bot pages

**Comment by Jaswir** [comment]
What do you mean? 
Which url?

**Comment by arshadkazmi42** [comment]
In [README](https://github.com/arshadkazmi42/first-issues#good-first-issues-bot-robot)

Link to twitter page and telegram group is a hyper link on texts, we would want to show twitter/telegram logo in place of text
