### ISSUE TITLE
Limting number of # tags in tweet

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/first-issues#59]
In this PR #53 we integrated languages #tags in tweet.
Some of the tweets have a huge number of tags due to which sometimes the tweet length is exceeding and API call to post a tweet is failing.
We need some limit to #tags used in the tweet. It should be dependent on the total length of the tweet and actual content should be present in the tweet

**Comment by arshadkazmi42** [comment]
@freddygcala Thanks again for #53 
Feel free to take this, if you are interested in working this. This is some extension on the changes you did in above PR.

**Comment by freddygcala** [comment]
Sure, I'll work on this
