### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/first-issues#7]
Add a `PULL_REQUEST_TEMPLATE.md` with following details

```
Fixes #issuenumber

Check everything which applies
[] I have added the issue number for which this pull request is created.
```

**Comment by SubhamPaul21** [comment]
i would like to help.... But i am a total new comer to open source contribution, So can you guide me?

**Comment by arshadkazmi42** [comment]
Go ahead create a PR.
You can follow these steps.
1. Fork this repo
2. Clone the forked repo
3. Create a new branch using `git checkout -b new_branch`
4. Create a new file in root directory with this name `PULL_REQUEST_TEMPLATE.md`
5. Add the contents mentioned in the issue details to the file
6. Commit and push your changes.
7. Open this repo in browser, you will get a option to create PR.
8. Create PR and you are done.

To understand the github workflow you can try completing the task in this repo https://github.com/firstcontributions/first-contributions

**Comment by SubhamPaul21** [comment]
ok working on this..... Will send a PR soon :)

**Comment by SubhamPaul21** [comment]
hey there... I forked and cloned the forked repo and made a new branch along with the file " PULL_REQUEST_TEMPLATE.md" in root directory.... Now i am confused as to what contents to add in the file? Can you please guide me .....

**Comment by arshadkazmi42** [comment]
You have to add this in the file
```
Fixes #issuenumber

Check everything which applies
[] I have added the issue number for which this pull request is created.
```

**Comment by SubhamPaul21** [comment]
thanks a lot.... will send PR right away

**Comment by SubhamPaul21** [comment]
sent a PR please have a look... I am excited as well as confused... first try .. haha
