### ISSUE TITLE
Add Logging Module

### ISSUE THREAD

**Issue by Pavithratrdev** [arshadkazmi42/first-issues#90]
Logs are also useful to detect common mistakes users make, as well as for security purposes. Writing good logs about a user's activity can alert us about harmful activity. It is important that logs can provide accurate context about what the user was doing when a specific error happened.

Reference Links:
https://realpython.com/python-logging/

**Comment by arshadkazmi42** [comment]
@Pavithratrdev This sounds good. 

Feel free to send a PR.

**Comment by Slok-e** [comment]
Hey, just wanted to know if this hadn't been addressed yet. I'd like to try and approach it?

**Comment by arshadkazmi42** [comment]
Hi @Slok-e 

@Pavithratrdev wanted to take this up. Let's check with them, if there is anywork started on this. Otherwise you can take this up.

@Pavithratrdev did you get chance to work on this? If not can you share details of the ticket so @Slok-e could take this up.

**Comment by Pavithratrdev** [comment]
Hi @arshadkazmi42 

We are held up with examination, need sometime to complete the same.
If @Slok-e is interested, please take this up.

**Comment by Slok-e** [comment]
@Pavithratrdev I'll start working on this immediately and ask questions as I get further in if there's anything specific you may be looking for. Thank you.

**Comment by sarthaknimbalkar** [comment]
Heyyy hiii I wanted to know if the issue is cleared or not, otherwise I would like to make a contribution.

**Comment by arshadkazmi42** [comment]
@sarthaknimbalkar I don't think anyone is working on it. Please go ahead.

**Comment by sarthaknimbalkar** [comment]
Thank you. I'll get back to you once done.
